/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cazucito.events;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // System.out.println(new Day01().task01());
        // System.out.println(new Day01().task02());
        // System.out.println(new Day02().task01());
        System.out.println(new Day02().task02());
    }
}
